name: Github Push back to gitea

on:
  push:
    branches:
      - main

jobs:
  Push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:nestv3
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

    - name: Runner Origin Check
      run: |
        if [ "${{ secrets.RUNNER_ORIGIN }}" = "github" ]; then
          true
        else
          exit 1
        fi
      env:
        RUNNER_ORIGIN: ${{ secrets.RUNNER_ORIGIN }}

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GITEA_SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Run
      run: git clone https://github.com/PikaOS-Linux/gitea-pikman-update-manager

    - name: Run
      run: ./gitea-pikman-update-manager/.github/github_pushback.sh
